[package]
name = "e2e-site-spawner"
version = "0.1.0"
authors = ["Sandy Figueroa <sandy@wp-media.me>"]
edition = "2024"

[[bin]]
name = "e2sp"
path = "src/main.rs"

# Dependencies
[dependencies]
clap = { version = "4.5.51", features = ["derive"] }
mysql = "26.0.1"
colored = "3.0.0"  # For colored terminal output
libc = "0.2.177"     # For Unix system calls
nix = { version = "0.30.1", features = ["user", "fs"] }

[dev-dependencies]
assert_cmd = "2.0"
predicates = "3.0"
tempfile = "3.23.0"
